version: '3.9'

services:
  nestapp:
    container_name: nestapp
    image: 664418982356.dkr.ecr.ap-south-1.amazonaws.com/nestapp:1.0.0
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      # Database Configuration
      DB_TYPE: postgres
      PG_HOST: database-1.cdisk4m8knsa.ap-south-1.rds.amazonaws.com
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DB: postgres
      PG_PORT: 5432

      # Redis Configuration
      REDIS_HOST: clustercfg.my.x2khqs.aps1.cache.amazonaws.com
      REDIS_PORT: 6379

      # JWT Secret
      JWT_SECRET: your_jwt_secret_key

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - nestapp
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "256M"

volumes:
  pgdata: {}
