version: '3.9'

services:
  nestapp:
    container_name: nestapp
    image: nestapp:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - JWT_SECRET=your_jwt_secret_key   # Add your JWT secret here
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db

volumes:
  pgdata: {}
